### ISSUE TITLE
Questions bout the feature shape transform during normalization

### ISSUE THREAD

**Issue by Xiao-xiaohei** [egrinstein/neural_srp#1]
Hello, after reading your code, i have some questions:

In GccExtractor,  the feat matric shape is

gcc_feat = np.zeros((nb_frames, self._nb_bins, n_output_channels))
gcc_feat = gcc_feat.transpose((0, 2, 1))

and, in Preprocessor::extract_all_feature, the feat is trans to

            feat = self._gcc_extractor(audio_in)
            nb_frames = feat.shape[1]
            feat = feat.transpose((0, 2, 1)).reshape((nb_frames, -1))

which not make sense. ( i mean, the nb_frames refers to different meanings

I can't get it, could u help me about it ？ If there is something wrong in this version of code? Thanks!!!

**Comment by egrinstein** [comment]
Hi,

Thank you very much for pointing this out.
You are correct. I just pushed a fix to this.

Best regards,

Eric
